config/routes.rb
Rails.application.routes.draw do
  resources :newspapers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "newspapers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :set_newspaper, only: %i[ show edit update destroy ]

  # GET /newspapers or /newspapers.json
  def index
    @newspapers = Newspaper.all
  end

  # GET /newspapers/1 or /newspapers/1.json
  def show
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  # POST /newspapers or /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to newspaper_url(@newspaper), notice: "Newspaper was successfully created." }
        format.json { render :show, status: :created, location: @newspaper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1 or /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to newspaper_url(@newspaper), notice: "Newspaper was successfully updated." }
        format.json { render :show, status: :ok, location: @newspaper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1 or /newspapers/1.json
  def destroy
    @newspaper.destroy

    respond_to do |format|
      format.html { redirect_to newspapers_url, notice: "Newspaper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newspaper_params
      params.require(:newspaper).permit(:encabezado, :cuerpo, :link, :tipo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grupal1v2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://architecture.nicepage.io/nicepage.css?version=c78727a8-d723-4db2-ac31-d0c881338ed8" media="screen">
    <script class="u-script" type="text/javascript" src="//static.nicepage.com/shared/assets/jquery-1.9.1.min.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="//capp.nicepage.com/04af837a941d1cfc5bc7ef8a193ff84e9ff9768c/nicepage.js" defer=""></script>
    
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700|Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=heading-font|text-font">
    <style class="u-style">.u-section-2 {
  background-image: linear-gradient(0deg, rgba(0,0,0,0.25), rgba(0,0,0,0.25)), url("//images03.nicepage.io/c461c07a441a5d220e8feb1a/8bc12c671b9d563f8ec408d8/pexels-photo-5990678.jpeg");
  background-position: 50% 100%;
}
.u-section-2 .u-sheet-1 {
  min-height: 740px;
}
.u-section-2 .u-text-1 {
  width: 800px;
  font-size: 3.75rem;
  margin: 60px auto 0;
}
.u-section-2 .u-text-2 {
  font-size: 1.25rem;
  font-style: italic;
  width: 800px;
  margin: 20px auto 0;
}
.u-section-2 .u-list-1 {
  min-height: 306px;
  grid-template-columns: repeat(4, calc(25% - 14px));
  grid-gap: 18px;
  margin: 57px 0 0;
}
.u-section-2 .u-list-item-1 {
  background-image: none;
}
.u-section-2 .u-container-layout-1 {
  padding: 30px;
}
.u-section-2 .u-image-1 {
  width: 164px;
  height: 164px;
  background-image: url("//images03.nicepage.io/c461c07a441a5d220e8feb1a/403d472a87e555e68834a6f2/low-angle-plain-concrete-structure-city-with-copy-space_23-2148814201.jpg");
  background-position: 50% 50%;
  margin: 0 auto;
}
.u-section-2 .u-text-3 {
  text-transform: none;
  font-style: italic;
  margin: 32px 2px 0;
}
.u-section-2 .u-container-layout-2 {
  padding: 30px;
}
.u-section-2 .u-image-2 {
  width: 164px;
  height: 164px;
  background-image: url("//images03.nicepage.io/c461c07a441a5d220e8feb1a/ce5afd0f2a5f5048a72e94df/low-angle-building-city_23-2148814160.jpg");
  background-position: 50% 50%;
  margin: 0 auto;
}
.u-section-2 .u-text-4 {
  text-transform: none;
  font-style: italic;
  margin: 32px 2px 0;
}
.u-section-2 .u-container-layout-3 {
  padding: 30px;
}
.u-section-2 .u-image-3 {
  width: 164px;
  height: 164px;
  background-image: url("//images03.nicepage.io/c461c07a441a5d220e8feb1a/03978994a9cf5ec8b64195f2/plain-concrete-structure-city-with-copy-space_23-2148814198.jpg");
  background-position: 50% 50%;
  margin: 0 auto;
}
.u-section-2 .u-text-5 {
  text-transform: none;
  font-style: italic;
  margin: 32px 2px 0;
}
.u-section-2 .u-container-layout-4 {
  padding: 30px;
}
.u-section-2 .u-image-4 {
  width: 164px;
  height: 164px;
  background-image: url("//images03.nicepage.io/c461c07a441a5d220e8feb1a/6b42a580ae8d57cbae739cc6/5da03891-cde7-5ff9-6ffe-2bdac41249d0.jpg?version=");
  background-position: 50% 50%;
  margin: 0 auto;
}
.u-section-2 .u-text-6 {
  text-transform: none;
  font-style: italic;
  margin: 32px 2px 0;
}
.u-section-2 .u-text-7 {
  width: 182px;
  margin: 39px auto 0;
}
.u-section-2 .u-btn-1 {
  border-style: none none solid;
  padding: 0;
}
.u-section-2 .u-btn-2 {
  background-image: none;
  border-style: solid;
  margin: 39px auto 60px;
}
@media (max-width: 1199px) {
  .u-section-2 .u-sheet-1 {
    min-height: 556px;
  }
  .u-section-2 .u-list-1 {
    min-height: 252px;
    margin-right: initial;
    margin-left: initial;
  }
  .u-section-2 .u-text-3 {
    margin-left: 0;
    margin-right: 0;
  }
  .u-section-2 .u-text-4 {
    margin-left: 0;
    margin-right: 0;
  }
  .u-section-2 .u-text-5 {
    margin-left: 0;
    margin-right: 0;
  }
  .u-section-2 .u-text-6 {
    margin-left: 0;
    margin-right: 0;
  }
}
@media (max-width: 991px) {
  .u-section-2 .u-sheet-1 {
    min-height: 1079px;
  }
  .u-section-2 .u-text-1 {
    width: 720px;
  }
  .u-section-2 .u-text-2 {
    width: 720px;
  }
  .u-section-2 .u-list-1 {
    min-height: 616px;
    grid-template-columns: repeat(2, calc(50% - 9.33333px));
    height: auto;
    margin-right: initial;
    margin-left: initial;
  }
  .u-section-2 .u-text-7 {
    margin-top: 38px;
  }
}
@media (max-width: 767px) {
  .u-section-2 .u-sheet-1 {
    min-height: 1076px;
  }
  .u-section-2 .u-text-1 {
    width: 540px;
    font-size: 3.4375rem;
  }
  .u-section-2 .u-text-2 {
    width: 540px;
  }
  .u-section-2 .u-list-1 {
    grid-template-columns: 100%;
    margin-right: initial;
    margin-left: initial;
  }
  .u-section-2 .u-container-layout-1 {
    padding-left: 10px;
    padding-right: 10px;
  }
  .u-section-2 .u-container-layout-2 {
    padding-left: 10px;
    padding-right: 10px;
  }
  .u-section-2 .u-container-layout-3 {
    padding-left: 10px;
    padding-right: 10px;
  }
  .u-section-2 .u-container-layout-4 {
    padding-left: 10px;
    padding-right: 10px;
  }
}
@media (max-width: 575px) {
  .u-section-2 .u-text-1 {
    width: 340px;
    font-size: 3rem;
  }
  .u-section-2 .u-text-2 {
    width: 340px;
  }
}</style>
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "https://architecture.nicepage.io/Page-1.html",
		"logo": "//capp.nicepage.com/04af837a941d1cfc5bc7ef8a193ff84e9ff9768c/images/default-logo.png",
		"sameAs": []
}</script>
    
    <link rel="canonical" href="https://architecture.nicepage.io/Page-1.html">
    <meta property="og:url" content="https://architecture.nicepage.io/Page-1.html">
  
</head>
  

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
  


    <%= yield %>
    </main>
  </body>
</html>

app/views/newspapers/_form.html.erb
<%= form_with(model: newspaper) do |form| %>
  <% if newspaper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(newspaper.errors.count, "error") %> prohibited this newspaper from being saved:</h2>

      <ul>
        <% newspaper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :encabezado, style: "display: block" %>
    <%= form.text_field :encabezado %>
  </div>

  <div>
    <%= form.label :cuerpo, style: "display: block" %>
    <%= form.text_field :cuerpo %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.number_field :tipo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/newspapers/_newspaper.html.erb
<div class="card" style="width:400px" id="<%= dom_id newspaper %>">
  <!--img class="card-img-top" src="img_avatar1.png" alt="Card image" style="width:100%"-->
  <div class="card-body">
   <% if newspaper.tipo == 1  %>
    <%= image_tag ("01deportes.jpg") %>
    <h4 class="card-title"> <% newspaper.tipo %>  <%= newspaper.encabezado %></h4>
    <p class="card-text"><%= newspaper.cuerpo %></p>
    <a href="#" class="btn btn-primary">   <%= newspaper.link %></a>
   <% end %>
  </div> 
</div>
 
 <div class="card" style="width:400px" id="<%= dom_id newspaper %>">
  <!--img class="card-img-top" src="img_avatar1.png" alt="Card image" style="width:100%"-->
  <div class="card-body">
   <% if newspaper.tipo == 2  %>
    <%= image_tag ("02farandula.jpg") %>
    <h4 class="card-title"> <% newspaper.tipo %>  <%= newspaper.encabezado %></h4>
    <p class="card-text"><%= newspaper.cuerpo %></p>
    <a href="#" class="btn btn-primary">   <%= newspaper.link %></a>
   <% end %>
  </div> 
</div>

<div class="card" style="width:400px" id="<%= dom_id newspaper %>">
  <!--img class="card-img-top" src="img_avatar1.png" alt="Card image" style="width:100%"-->
  <div class="card-body">
   <% if newspaper.tipo == 3  %>
    <%= image_tag ("03nacional.jpg") %>
    <h4 class="card-title"> <% newspaper.tipo %>  <%= newspaper.encabezado %></h4>
    <p class="card-text"><%= newspaper.cuerpo %></p>
    <a href="#" class="btn btn-primary">   <%= newspaper.link %></a>
   <% end %>
  </div> 
</div>

<div class="card" style="width:400px" id="<%= dom_id newspaper %>">
  <!--img class="card-img-top" src="img_avatar1.png" alt="Card image" style="width:100%"-->
  <div class="card-body">
   <% if newspaper.tipo == 4  %>
    <%= image_tag ("04internacional.jpg") %>
    <h4 class="card-title"> <% newspaper.tipo %>  <%= newspaper.encabezado %></h4>
    <p class="card-text"><%= newspaper.cuerpo %></p>
    <a href="#" class="btn btn-primary">   <%= newspaper.link %></a>
   <% end %>
  </div> 
</div>

<div class="card" style="width:400px" id="<%= dom_id newspaper %>">
  <!--img class="card-img-top" src="img_avatar1.png" alt="Card image" style="width:100%"-->
  <div class="card-body">
   <% if newspaper.tipo == 5  %>
    <%= image_tag ("05politica.jpg") %>
    <h4 class="card-title"> <% newspaper.tipo %>  <%= newspaper.encabezado %></h4>
    <p class="card-text"><%= newspaper.cuerpo %></p>
    <a href="#" class="btn btn-primary">   <%= newspaper.link %></a>
   <% end %>
  </div> 
</div>

app/views/newspapers/edit.html.erb
<h1>Editando esta noticia</h1>

<%= render "form", newspaper: @newspaper %>

<br>

<div>
  <%= link_to "Mostrar esta noticia", @newspaper %> |
  <%= link_to "Volver a noticias", newspapers_path %>
</div>

app/views/newspapers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Noticias</h1>
<div class="u-align-center u-container-style u-list-item u-repeater-item u-video-cover u-white">
  <div class="u-container-layout u-similar-container u-container-layout-3">
  <div alt="" class="u-image u-image-circle u-image-3"></div>
    <h4 class="u-text u-text-5">Revisa las últimas noticias positivas en Chile y el mundo</h4>
    <%= image_tag ("01deportes.jpg") %>
    <%= image_tag ("02farandula.jpg") %>
    <%= image_tag ("03nacional.jpg") %>
    <%= image_tag ("04internacional.jpg") %>
    <%= image_tag ("05politica.jpg") %>

  </div>
  </div>



<div id="newspapers">
  <% @newspapers.each do |newspaper| %>
    <%= render newspaper %> 
    <p>
      <%= link_to "Mostrar esta noticia", newspaper %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva noticia", new_newspaper_path %>

app/views/newspapers/new.html.erb
<h1>Nueva noticia</h1>

<%= render "form", newspaper: @newspaper %>

<br>

<div>
  <%= link_to "Volver a noticias", newspapers_path %>
</div>

app/views/newspapers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @newspaper %>

<div>
  <%= link_to "Editando esta noticia", edit_newspaper_path(@newspaper) %> |
  <%= link_to "Volver a noticias", newspapers_path %>

  <%= button_to "Destruir esta noticia", @newspaper, method: :delete %>
</div>